# Generated by Django 4.1.7 on 2023-03-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
