# Generated by Django 4.1.7 on 2023-03-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_device_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='slug',
        ),
    ]
