# Generated by Django 4.1.7 on 2023-03-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_device_slug'),
        ('employee', '0002_remove_employee_device_employee_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='device',
        ),
        migrations.AddField(
            model_name='employee',
            name='device',
            field=models.ManyToManyField(to='company.device'),
        ),
    ]
