# Generated by Django 4.1.7 on 2023-03-08 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_device_slug'),
        ('employee', '0003_remove_employee_device_employee_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='device',
        ),
        migrations.AddField(
            model_name='employee',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.device'),
        ),
    ]
