# Generated by Django 4.1.7 on 2023-03-11 16:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_device_slug'),
        ('employee', '0006_device_return_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Feedback',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('SSLcommerz', 'SSLcommerz')], default=('SSLcommerz', 'SSLcommerz'), max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Device_Return',
        ),
    ]
