# Generated by Django 4.1.7 on 2023-03-11 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_device_feedback_payment_delete_device_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_feedback',
            name='employee_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
