# Generated by Django 4.1.7 on 2023-03-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_employee_paymentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ReturnID',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
